# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ProgramProjects\ICCD1.0\aquisition_setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_aquisition_setup(object):
    def setupUi(self, aquisition_setup):
        aquisition_setup.setObjectName("aquisition_setup")
        aquisition_setup.resize(613, 327)
        aquisition_setup.setMinimumSize(QtCore.QSize(613, 0))
        aquisition_setup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico_file/1117367.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        aquisition_setup.setWindowIcon(icon)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(aquisition_setup)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(aquisition_setup)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_measure_mode = QtWidgets.QComboBox(self.tab)
        self.comboBox_measure_mode.setObjectName("comboBox_measure_mode")
        self.comboBox_measure_mode.addItem("")
        self.comboBox_measure_mode.addItem("")
        self.comboBox_measure_mode.addItem("")
        self.gridLayout.addWidget(self.comboBox_measure_mode, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_trigger_mode = QtWidgets.QComboBox(self.tab)
        self.comboBox_trigger_mode.setObjectName("comboBox_trigger_mode")
        self.comboBox_trigger_mode.addItem("")
        self.comboBox_trigger_mode.addItem("")
        self.gridLayout.addWidget(self.comboBox_trigger_mode, 1, 2, 1, 1)
        self.comboBox_readout_mode = QtWidgets.QComboBox(self.tab)
        self.comboBox_readout_mode.setObjectName("comboBox_readout_mode")
        self.comboBox_readout_mode.addItem("")
        self.gridLayout.addWidget(self.comboBox_readout_mode, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.doubleSpinBox_exposure_time = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_exposure_time.setDecimals(5)
        self.doubleSpinBox_exposure_time.setMinimum(0.00025)
        self.doubleSpinBox_exposure_time.setMaximum(30.0)
        self.doubleSpinBox_exposure_time.setSingleStep(0.001)
        self.doubleSpinBox_exposure_time.setObjectName("doubleSpinBox_exposure_time")
        self.gridLayout_7.addWidget(self.doubleSpinBox_exposure_time, 0, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_7)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_35 = QtWidgets.QLabel(self.widget_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_8.addWidget(self.label_35)
        self.spinBox_threshold = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_threshold.setMaximum(255)
        self.spinBox_threshold.setObjectName("spinBox_threshold")
        self.horizontalLayout_8.addWidget(self.spinBox_threshold)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.widget_total_frame_count = QtWidgets.QWidget(self.groupBox_6)
        self.widget_total_frame_count.setObjectName("widget_total_frame_count")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_total_frame_count)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.widget_total_frame_count)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.spinBox_frame_count = QtWidgets.QSpinBox(self.widget_total_frame_count)
        self.spinBox_frame_count.setMinimum(1)
        self.spinBox_frame_count.setMaximum(1000000)
        self.spinBox_frame_count.setProperty("value", 1)
        self.spinBox_frame_count.setObjectName("spinBox_frame_count")
        self.gridLayout_2.addWidget(self.spinBox_frame_count, 0, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_2)
        self.verticalLayout_13.addWidget(self.widget_total_frame_count)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_frame_rate = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_frame_rate.setObjectName("comboBox_frame_rate")
        self.gridLayout_6.addWidget(self.comboBox_frame_rate, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.doubleSpinBox_pre_gain = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_pre_gain.setMaximum(48.0)
        self.doubleSpinBox_pre_gain.setObjectName("doubleSpinBox_pre_gain")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pre_gain, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_internal_trigger = QtWidgets.QWidget(self.groupBox_8)
        self.widget_internal_trigger.setObjectName("widget_internal_trigger")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_internal_trigger)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_33 = QtWidgets.QLabel(self.widget_internal_trigger)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.doubleSpinBox_internal_trigger_rate = QtWidgets.QDoubleSpinBox(self.widget_internal_trigger)
        self.doubleSpinBox_internal_trigger_rate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_internal_trigger_rate.setMaximum(1000000.0)
        self.doubleSpinBox_internal_trigger_rate.setObjectName("doubleSpinBox_internal_trigger_rate")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_internal_trigger_rate)
        self.comboBox_internal_trigger_rate_unit = QtWidgets.QComboBox(self.widget_internal_trigger)
        self.comboBox_internal_trigger_rate_unit.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_internal_trigger_rate_unit.setObjectName("comboBox_internal_trigger_rate_unit")
        self.comboBox_internal_trigger_rate_unit.addItem("")
        self.comboBox_internal_trigger_rate_unit.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_internal_trigger_rate_unit)
        self.verticalLayout_20.addLayout(self.horizontalLayout_6)
        self.verticalLayout_17.addWidget(self.widget_internal_trigger)
        self.widget_external_trigger = QtWidgets.QWidget(self.groupBox_8)
        self.widget_external_trigger.setObjectName("widget_external_trigger")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_external_trigger)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_18 = QtWidgets.QLabel(self.widget_external_trigger)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 1, 0, 1, 1)
        self.comboBox_trigger_edge = QtWidgets.QComboBox(self.widget_external_trigger)
        self.comboBox_trigger_edge.setObjectName("comboBox_trigger_edge")
        self.comboBox_trigger_edge.addItem("")
        self.comboBox_trigger_edge.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_trigger_edge, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_external_trigger)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_external_trigger)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 3, 0, 1, 1)
        self.comboBox_trigger_impedance = QtWidgets.QComboBox(self.widget_external_trigger)
        self.comboBox_trigger_impedance.setObjectName("comboBox_trigger_impedance")
        self.comboBox_trigger_impedance.addItem("")
        self.comboBox_trigger_impedance.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_trigger_impedance, 2, 1, 1, 1)
        self.doubleSpinBox_trigger_level = QtWidgets.QDoubleSpinBox(self.widget_external_trigger)
        self.doubleSpinBox_trigger_level.setMaximum(3.0)
        self.doubleSpinBox_trigger_level.setSingleStep(0.1)
        self.doubleSpinBox_trigger_level.setObjectName("doubleSpinBox_trigger_level")
        self.gridLayout_8.addWidget(self.doubleSpinBox_trigger_level, 3, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_external_trigger)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 0, 0, 1, 1)
        self.doubleSpinBox_divisor = QtWidgets.QDoubleSpinBox(self.widget_external_trigger)
        self.doubleSpinBox_divisor.setMaximum(1000000000.0)
        self.doubleSpinBox_divisor.setObjectName("doubleSpinBox_divisor")
        self.gridLayout_8.addWidget(self.doubleSpinBox_divisor, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.verticalLayout_17.addWidget(self.widget_external_trigger)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.groupBox_8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinBox_mcp_gain = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_mcp_gain.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_mcp_gain.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.spinBox_mcp_gain.setMaximum(4095)
        self.spinBox_mcp_gain.setSingleStep(100)
        self.spinBox_mcp_gain.setObjectName("spinBox_mcp_gain")
        self.gridLayout_3.addWidget(self.spinBox_mcp_gain, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_enable_ioc = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_enable_ioc.setObjectName("checkBox_enable_ioc")
        self.verticalLayout_7.addWidget(self.checkBox_enable_ioc)
        self.widget_IOC = QtWidgets.QWidget(self.groupBox_3)
        self.widget_IOC.setObjectName("widget_IOC")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_IOC)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.radioButton_fit_ccd = QtWidgets.QRadioButton(self.widget_IOC)
        self.radioButton_fit_ccd.setObjectName("radioButton_fit_ccd")
        self.verticalLayout_8.addWidget(self.radioButton_fit_ccd)
        self.radioButton_burst = QtWidgets.QRadioButton(self.widget_IOC)
        self.radioButton_burst.setChecked(True)
        self.radioButton_burst.setObjectName("radioButton_burst")
        self.verticalLayout_8.addWidget(self.radioButton_burst)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_burst_count = QtWidgets.QSpinBox(self.widget_IOC)
        self.spinBox_burst_count.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_burst_count.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.spinBox_burst_count.setMinimum(1)
        self.spinBox_burst_count.setMaximum(1000000)
        self.spinBox_burst_count.setObjectName("spinBox_burst_count")
        self.horizontalLayout.addWidget(self.spinBox_burst_count)
        self.label_8 = QtWidgets.QLabel(self.widget_IOC)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.widget_IOC)
        self.verticalLayout_19.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_output = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget_output.setObjectName("tabWidget_output")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.doubleSpinBox_width_d = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_width_d.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_width_d.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.doubleSpinBox_width_d.setMaximum(1000000000.0)
        self.doubleSpinBox_width_d.setObjectName("doubleSpinBox_width_d")
        self.gridLayout_9.addWidget(self.doubleSpinBox_width_d, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBox_delay_d = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_delay_d.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_delay_d.setObjectName("comboBox_delay_d")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_delay_d, 0, 2, 1, 1)
        self.comboBox_width_d = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_width_d.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_width_d.setObjectName("comboBox_width_d")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_width_d, 1, 2, 1, 1)
        self.doubleSpinBox_delay_d = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_delay_d.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_delay_d.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.doubleSpinBox_delay_d.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_d.setObjectName("doubleSpinBox_delay_d")
        self.gridLayout_9.addWidget(self.doubleSpinBox_delay_d, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tabWidget_output.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_channel_enable_a = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_channel_enable_a.setObjectName("checkBox_channel_enable_a")
        self.verticalLayout_2.addWidget(self.checkBox_channel_enable_a)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.doubleSpinBox_width_a = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_width_a.setEnabled(False)
        self.doubleSpinBox_width_a.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_width_a.setMaximum(1000000000.0)
        self.doubleSpinBox_width_a.setObjectName("doubleSpinBox_width_a")
        self.gridLayout_10.addWidget(self.doubleSpinBox_width_a, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 1, 0, 1, 1)
        self.comboBox_delay_a = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_delay_a.setEnabled(False)
        self.comboBox_delay_a.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_delay_a.setObjectName("comboBox_delay_a")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_delay_a, 0, 2, 1, 1)
        self.comboBox_width_a = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_width_a.setEnabled(False)
        self.comboBox_width_a.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_width_a.setObjectName("comboBox_width_a")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_width_a, 1, 2, 1, 1)
        self.doubleSpinBox_delay_a = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_delay_a.setEnabled(False)
        self.doubleSpinBox_delay_a.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_delay_a.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_a.setObjectName("doubleSpinBox_delay_a")
        self.gridLayout_10.addWidget(self.doubleSpinBox_delay_a, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 2, 0, 1, 1)
        self.comboBox_polarity_a = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_polarity_a.setEnabled(False)
        self.comboBox_polarity_a.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_polarity_a.setObjectName("comboBox_polarity_a")
        self.comboBox_polarity_a.addItem("")
        self.comboBox_polarity_a.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_polarity_a, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.checkBox_same_to_gate_a = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_same_to_gate_a.setEnabled(False)
        self.checkBox_same_to_gate_a.setObjectName("checkBox_same_to_gate_a")
        self.verticalLayout_2.addWidget(self.checkBox_same_to_gate_a)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.tabWidget_output.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_channel_enable_b = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_channel_enable_b.setObjectName("checkBox_channel_enable_b")
        self.verticalLayout_3.addWidget(self.checkBox_channel_enable_b)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.doubleSpinBox_width_b = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox_width_b.setEnabled(False)
        self.doubleSpinBox_width_b.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_width_b.setMaximum(1000000000.0)
        self.doubleSpinBox_width_b.setObjectName("doubleSpinBox_width_b")
        self.gridLayout_11.addWidget(self.doubleSpinBox_width_b, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 1, 0, 1, 1)
        self.comboBox_delay_b = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_delay_b.setEnabled(False)
        self.comboBox_delay_b.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_delay_b.setObjectName("comboBox_delay_b")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_delay_b, 0, 2, 1, 1)
        self.comboBox_width_b = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_width_b.setEnabled(False)
        self.comboBox_width_b.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_width_b.setObjectName("comboBox_width_b")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_width_b, 1, 2, 1, 1)
        self.doubleSpinBox_delay_b = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox_delay_b.setEnabled(False)
        self.doubleSpinBox_delay_b.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_delay_b.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_b.setObjectName("doubleSpinBox_delay_b")
        self.gridLayout_11.addWidget(self.doubleSpinBox_delay_b, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 2, 0, 1, 1)
        self.comboBox_polarity_b = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_polarity_b.setEnabled(False)
        self.comboBox_polarity_b.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_polarity_b.setObjectName("comboBox_polarity_b")
        self.comboBox_polarity_b.addItem("")
        self.comboBox_polarity_b.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_polarity_b, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.checkBox_same_to_gate_b = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_same_to_gate_b.setEnabled(False)
        self.checkBox_same_to_gate_b.setObjectName("checkBox_same_to_gate_b")
        self.verticalLayout_3.addWidget(self.checkBox_same_to_gate_b)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.tabWidget_output.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_channel_enable_c = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_channel_enable_c.setObjectName("checkBox_channel_enable_c")
        self.verticalLayout_4.addWidget(self.checkBox_channel_enable_c)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.doubleSpinBox_width_c = QtWidgets.QDoubleSpinBox(self.tab_8)
        self.doubleSpinBox_width_c.setEnabled(False)
        self.doubleSpinBox_width_c.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_width_c.setMaximum(1000000000.0)
        self.doubleSpinBox_width_c.setObjectName("doubleSpinBox_width_c")
        self.gridLayout_12.addWidget(self.doubleSpinBox_width_c, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_8)
        self.label_28.setObjectName("label_28")
        self.gridLayout_12.addWidget(self.label_28, 1, 0, 1, 1)
        self.comboBox_delay_c = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_delay_c.setEnabled(False)
        self.comboBox_delay_c.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_delay_c.setObjectName("comboBox_delay_c")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_delay_c, 0, 2, 1, 1)
        self.comboBox_width_c = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_width_c.setEnabled(False)
        self.comboBox_width_c.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_width_c.setObjectName("comboBox_width_c")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_width_c, 1, 2, 1, 1)
        self.doubleSpinBox_delay_c = QtWidgets.QDoubleSpinBox(self.tab_8)
        self.doubleSpinBox_delay_c.setEnabled(False)
        self.doubleSpinBox_delay_c.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_delay_c.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_c.setObjectName("doubleSpinBox_delay_c")
        self.gridLayout_12.addWidget(self.doubleSpinBox_delay_c, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_8)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_12.addWidget(self.label_30, 2, 0, 1, 1)
        self.comboBox_polarity_c = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_polarity_c.setEnabled(False)
        self.comboBox_polarity_c.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_polarity_c.setObjectName("comboBox_polarity_c")
        self.comboBox_polarity_c.addItem("")
        self.comboBox_polarity_c.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_polarity_c, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_12)
        self.checkBox_same_to_gate_c = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_same_to_gate_c.setEnabled(False)
        self.checkBox_same_to_gate_c.setObjectName("checkBox_same_to_gate_c")
        self.verticalLayout_4.addWidget(self.checkBox_same_to_gate_c)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.tabWidget_output.addTab(self.tab_8, "")
        self.verticalLayout_6.addWidget(self.tabWidget_output)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBox_roi_bottom = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_bottom.setMaximum(1200)
        self.spinBox_roi_bottom.setObjectName("spinBox_roi_bottom")
        self.gridLayout_4.addWidget(self.spinBox_roi_bottom, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 2, 1, 1)
        self.spinBox_roi_left = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_left.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_left.setMaximum(1920)
        self.spinBox_roi_left.setObjectName("spinBox_roi_left")
        self.gridLayout_4.addWidget(self.spinBox_roi_left, 0, 1, 1, 1)
        self.spinBox_roi_right = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_right.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_right.setMaximum(1920)
        self.spinBox_roi_right.setObjectName("spinBox_roi_right")
        self.gridLayout_4.addWidget(self.spinBox_roi_right, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinBox_roi_top = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_top.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_top.setMaximum(1200)
        self.spinBox_roi_top.setObjectName("spinBox_roi_top")
        self.gridLayout_4.addWidget(self.spinBox_roi_top, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 2, 1, 1)
        self.spinBox_roi_height = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_height.setEnabled(False)
        self.spinBox_roi_height.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_height.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_roi_height.setMaximum(1200)
        self.spinBox_roi_height.setObjectName("spinBox_roi_height")
        self.gridLayout_4.addWidget(self.spinBox_roi_height, 2, 3, 1, 1)
        self.spinBox_roi_width = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_roi_width.setEnabled(False)
        self.spinBox_roi_width.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_roi_width.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_roi_width.setMaximum(1920)
        self.spinBox_roi_width.setObjectName("spinBox_roi_width")
        self.gridLayout_4.addWidget(self.spinBox_roi_width, 2, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_roi_sure = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_roi_sure.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_roi_sure.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_roi_sure.setFont(font)
        self.pushButton_roi_sure.setObjectName("pushButton_roi_sure")
        self.horizontalLayout_2.addWidget(self.pushButton_roi_sure)
        self.pushButton_revoke = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_revoke.setEnabled(True)
        self.pushButton_revoke.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pushButton_revoke.setObjectName("pushButton_revoke")
        self.horizontalLayout_2.addWidget(self.pushButton_revoke)
        self.pushButton_roi_resume = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_roi_resume.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_roi_resume.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_roi_resume.setFont(font)
        self.pushButton_roi_resume.setObjectName("pushButton_roi_resume")
        self.horizontalLayout_2.addWidget(self.pushButton_roi_resume)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.radioButton_binning1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_binning1.setChecked(True)
        self.radioButton_binning1.setObjectName("radioButton_binning1")
        self.verticalLayout_15.addWidget(self.radioButton_binning1)
        self.radioButton_binning2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_binning2.setObjectName("radioButton_binning2")
        self.verticalLayout_15.addWidget(self.radioButton_binning2)
        self.radioButton_binning3 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_binning3.setObjectName("radioButton_binning3")
        self.verticalLayout_15.addWidget(self.radioButton_binning3)
        self.radioButton_binning4 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_binning4.setObjectName("radioButton_binning4")
        self.verticalLayout_15.addWidget(self.radioButton_binning4)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_15.addWidget(self.label_32)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_enable_autosave = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_enable_autosave.setObjectName("checkBox_enable_autosave")
        self.verticalLayout_11.addWidget(self.checkBox_enable_autosave)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setEnabled(False)
        self.widget.setObjectName("widget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.gridLayout_5.addWidget(self.lineEdit_file_name, 1, 1, 1, 1)
        self.checkBox_date = QtWidgets.QCheckBox(self.widget)
        self.checkBox_date.setObjectName("checkBox_date")
        self.gridLayout_5.addWidget(self.checkBox_date, 3, 0, 1, 1)
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.gridLayout_5.addWidget(self.lineEdit_file_path, 2, 1, 1, 1)
        self.pushButton_choose_filepath = QtWidgets.QPushButton(self.widget)
        self.pushButton_choose_filepath.setObjectName("pushButton_choose_filepath")
        self.gridLayout_5.addWidget(self.pushButton_choose_filepath, 2, 0, 1, 1)
        self.comboBox_file_format = QtWidgets.QComboBox(self.widget)
        self.comboBox_file_format.setObjectName("comboBox_file_format")
        self.comboBox_file_format.addItem("")
        self.comboBox_file_format.addItem("")
        self.comboBox_file_format.addItem("")
        self.comboBox_file_format.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_file_format, 0, 1, 1, 1)
        self.checkBox_operator = QtWidgets.QCheckBox(self.widget)
        self.checkBox_operator.setObjectName("checkBox_operator")
        self.gridLayout_5.addWidget(self.checkBox_operator, 4, 0, 1, 1)
        self.lineEdit_operator = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_operator.setObjectName("lineEdit_operator")
        self.gridLayout_5.addWidget(self.lineEdit_operator, 4, 1, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_5)
        self.verticalLayout_11.addWidget(self.widget)
        spacerItem10 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_7.addWidget(self.tabWidget)

        self.retranslateUi(aquisition_setup)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_output.setCurrentIndex(1)
        self.checkBox_enable_ioc.toggled['bool'].connect(self.widget_IOC.setVisible)
        self.radioButton_burst.toggled['bool'].connect(self.spinBox_burst_count.setEnabled)
        self.checkBox_enable_autosave.toggled['bool'].connect(self.widget.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.doubleSpinBox_delay_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.doubleSpinBox_width_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.comboBox_polarity_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.comboBox_delay_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.comboBox_width_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.checkBox_same_to_gate_a.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.doubleSpinBox_delay_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.checkBox_same_to_gate_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.doubleSpinBox_width_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.comboBox_polarity_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.comboBox_delay_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.comboBox_width_b.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.checkBox_same_to_gate_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.doubleSpinBox_delay_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.doubleSpinBox_width_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.comboBox_polarity_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.comboBox_delay_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.comboBox_width_c.setEnabled)
        self.tabWidget.windowTitleChanged['QString'].connect(self.widget_total_frame_count.hide)
        self.tabWidget.windowTitleChanged['QString'].connect(self.widget_external_trigger.hide)
        self.tabWidget.windowTitleChanged['QString'].connect(self.widget_IOC.hide)
        QtCore.QMetaObject.connectSlotsByName(aquisition_setup)
        aquisition_setup.setTabOrder(self.comboBox_measure_mode, self.doubleSpinBox_exposure_time)
        aquisition_setup.setTabOrder(self.doubleSpinBox_exposure_time, self.spinBox_frame_count)
        aquisition_setup.setTabOrder(self.spinBox_frame_count, self.comboBox_frame_rate)
        aquisition_setup.setTabOrder(self.comboBox_frame_rate, self.doubleSpinBox_pre_gain)
        aquisition_setup.setTabOrder(self.doubleSpinBox_pre_gain, self.spinBox_mcp_gain)
        aquisition_setup.setTabOrder(self.spinBox_mcp_gain, self.checkBox_enable_ioc)
        aquisition_setup.setTabOrder(self.checkBox_enable_ioc, self.radioButton_fit_ccd)
        aquisition_setup.setTabOrder(self.radioButton_fit_ccd, self.radioButton_burst)
        aquisition_setup.setTabOrder(self.radioButton_burst, self.spinBox_burst_count)
        aquisition_setup.setTabOrder(self.spinBox_burst_count, self.tabWidget_output)
        aquisition_setup.setTabOrder(self.tabWidget_output, self.doubleSpinBox_delay_d)
        aquisition_setup.setTabOrder(self.doubleSpinBox_delay_d, self.comboBox_delay_d)
        aquisition_setup.setTabOrder(self.comboBox_delay_d, self.doubleSpinBox_width_d)
        aquisition_setup.setTabOrder(self.doubleSpinBox_width_d, self.comboBox_width_d)
        aquisition_setup.setTabOrder(self.comboBox_width_d, self.spinBox_roi_left)
        aquisition_setup.setTabOrder(self.spinBox_roi_left, self.spinBox_roi_right)
        aquisition_setup.setTabOrder(self.spinBox_roi_right, self.spinBox_roi_bottom)
        aquisition_setup.setTabOrder(self.spinBox_roi_bottom, self.spinBox_roi_top)
        aquisition_setup.setTabOrder(self.spinBox_roi_top, self.radioButton_binning1)
        aquisition_setup.setTabOrder(self.radioButton_binning1, self.radioButton_binning2)
        aquisition_setup.setTabOrder(self.radioButton_binning2, self.checkBox_enable_autosave)
        aquisition_setup.setTabOrder(self.checkBox_enable_autosave, self.comboBox_file_format)
        aquisition_setup.setTabOrder(self.comboBox_file_format, self.lineEdit_file_name)
        aquisition_setup.setTabOrder(self.lineEdit_file_name, self.pushButton_choose_filepath)
        aquisition_setup.setTabOrder(self.pushButton_choose_filepath, self.lineEdit_file_path)
        aquisition_setup.setTabOrder(self.lineEdit_file_path, self.checkBox_date)
        aquisition_setup.setTabOrder(self.checkBox_date, self.checkBox_operator)
        aquisition_setup.setTabOrder(self.checkBox_operator, self.lineEdit_operator)
        aquisition_setup.setTabOrder(self.lineEdit_operator, self.doubleSpinBox_delay_c)
        aquisition_setup.setTabOrder(self.doubleSpinBox_delay_c, self.comboBox_polarity_c)
        aquisition_setup.setTabOrder(self.comboBox_polarity_c, self.checkBox_same_to_gate_c)
        aquisition_setup.setTabOrder(self.checkBox_same_to_gate_c, self.comboBox_delay_b)
        aquisition_setup.setTabOrder(self.comboBox_delay_b, self.doubleSpinBox_delay_a)
        aquisition_setup.setTabOrder(self.doubleSpinBox_delay_a, self.comboBox_polarity_a)
        aquisition_setup.setTabOrder(self.comboBox_polarity_a, self.checkBox_same_to_gate_a)
        aquisition_setup.setTabOrder(self.checkBox_same_to_gate_a, self.checkBox_channel_enable_b)
        aquisition_setup.setTabOrder(self.checkBox_channel_enable_b, self.checkBox_channel_enable_a)
        aquisition_setup.setTabOrder(self.checkBox_channel_enable_a, self.comboBox_delay_a)
        aquisition_setup.setTabOrder(self.comboBox_delay_a, self.doubleSpinBox_width_b)
        aquisition_setup.setTabOrder(self.doubleSpinBox_width_b, self.doubleSpinBox_width_a)
        aquisition_setup.setTabOrder(self.doubleSpinBox_width_a, self.comboBox_width_a)
        aquisition_setup.setTabOrder(self.comboBox_width_a, self.comboBox_width_b)
        aquisition_setup.setTabOrder(self.comboBox_width_b, self.comboBox_polarity_b)
        aquisition_setup.setTabOrder(self.comboBox_polarity_b, self.doubleSpinBox_width_c)
        aquisition_setup.setTabOrder(self.doubleSpinBox_width_c, self.checkBox_channel_enable_c)
        aquisition_setup.setTabOrder(self.checkBox_channel_enable_c, self.checkBox_same_to_gate_b)
        aquisition_setup.setTabOrder(self.checkBox_same_to_gate_b, self.doubleSpinBox_delay_b)
        aquisition_setup.setTabOrder(self.doubleSpinBox_delay_b, self.comboBox_delay_c)
        aquisition_setup.setTabOrder(self.comboBox_delay_c, self.comboBox_width_c)
        self.tabWidget.setWindowTitle("config")


    def retranslateUi(self, aquisition_setup):
        _translate = QtCore.QCoreApplication.translate
        aquisition_setup.setWindowTitle(_translate("aquisition_setup", "采集设置"))
        self.comboBox_measure_mode.setItemText(0, _translate("aquisition_setup", "单次"))
        self.comboBox_measure_mode.setItemText(1, _translate("aquisition_setup", "累加"))
        self.comboBox_measure_mode.setItemText(2, _translate("aquisition_setup", "光子计数"))
        self.label.setText(_translate("aquisition_setup", "采集模式"))
        self.comboBox_trigger_mode.setItemText(0, _translate("aquisition_setup", "内触发"))
        self.comboBox_trigger_mode.setItemText(1, _translate("aquisition_setup", "外触发"))
        self.comboBox_readout_mode.setItemText(0, _translate("aquisition_setup", "图像"))
        self.label_2.setText(_translate("aquisition_setup", "触发模式"))
        self.label_3.setText(_translate("aquisition_setup", "读出模式"))
        self.groupBox_6.setTitle(_translate("aquisition_setup", "计时设置"))
        self.label_4.setText(_translate("aquisition_setup", "曝光时间(S)"))
        self.label_35.setText(_translate("aquisition_setup", "阈值"))
        self.label_15.setText(_translate("aquisition_setup", "帧数"))
        self.groupBox_7.setTitle(_translate("aquisition_setup", "读出设置"))
        self.label_5.setText(_translate("aquisition_setup", "读出速率"))
        self.label_6.setText(_translate("aquisition_setup", "前置增益(0-48)"))
        self.groupBox_8.setTitle(_translate("aquisition_setup", "触发设置"))
        self.label_33.setText(_translate("aquisition_setup", "频率"))
        self.comboBox_internal_trigger_rate_unit.setItemText(0, _translate("aquisition_setup", " HZ"))
        self.comboBox_internal_trigger_rate_unit.setItemText(1, _translate("aquisition_setup", "KHZ"))
        self.label_18.setText(_translate("aquisition_setup", "边沿"))
        self.comboBox_trigger_edge.setItemText(0, _translate("aquisition_setup", "上升沿"))
        self.comboBox_trigger_edge.setItemText(1, _translate("aquisition_setup", "下降沿"))
        self.label_21.setText(_translate("aquisition_setup", "阻抗"))
        self.label_31.setText(_translate("aquisition_setup", "阈值(0-3V)"))
        self.comboBox_trigger_impedance.setItemText(0, _translate("aquisition_setup", "50Ω"))
        self.comboBox_trigger_impedance.setItemText(1, _translate("aquisition_setup", "HIZ"))
        self.label_34.setText(_translate("aquisition_setup", "分频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("aquisition_setup", "相机设置"))
        self.groupBox.setTitle(_translate("aquisition_setup", "MCP"))
        self.label_7.setText(_translate("aquisition_setup", "增益(0-4095)"))
        self.groupBox_3.setTitle(_translate("aquisition_setup", "片上积分"))
        self.checkBox_enable_ioc.setText(_translate("aquisition_setup", "开启"))
        self.radioButton_fit_ccd.setText(_translate("aquisition_setup", "适配CCD"))
        self.radioButton_burst.setText(_translate("aquisition_setup", "Burst"))
        self.label_8.setText(_translate("aquisition_setup", "个脉冲每次曝光"))
        self.groupBox_2.setTitle(_translate("aquisition_setup", "延时控制"))
        self.label_19.setText(_translate("aquisition_setup", "脉宽"))
        self.comboBox_delay_d.setItemText(0, _translate("aquisition_setup", "ps"))
        self.comboBox_delay_d.setItemText(1, _translate("aquisition_setup", "ns"))
        self.comboBox_delay_d.setItemText(2, _translate("aquisition_setup", "us"))
        self.comboBox_delay_d.setItemText(3, _translate("aquisition_setup", "ms"))
        self.comboBox_delay_d.setItemText(4, _translate("aquisition_setup", "s"))
        self.comboBox_width_d.setItemText(0, _translate("aquisition_setup", "ns"))
        self.comboBox_width_d.setItemText(1, _translate("aquisition_setup", "us"))
        self.comboBox_width_d.setItemText(2, _translate("aquisition_setup", "ms"))
        self.comboBox_width_d.setItemText(3, _translate("aquisition_setup", "s"))
        self.label_20.setText(_translate("aquisition_setup", "延时"))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.tab_5), _translate("aquisition_setup", "门控"))
        self.checkBox_channel_enable_a.setText(_translate("aquisition_setup", "开启"))
        self.label_22.setText(_translate("aquisition_setup", "脉宽"))
        self.comboBox_delay_a.setItemText(0, _translate("aquisition_setup", "ps"))
        self.comboBox_delay_a.setItemText(1, _translate("aquisition_setup", "ns"))
        self.comboBox_delay_a.setItemText(2, _translate("aquisition_setup", "us"))
        self.comboBox_delay_a.setItemText(3, _translate("aquisition_setup", "ms"))
        self.comboBox_delay_a.setItemText(4, _translate("aquisition_setup", "s"))
        self.comboBox_width_a.setItemText(0, _translate("aquisition_setup", "ns"))
        self.comboBox_width_a.setItemText(1, _translate("aquisition_setup", "us"))
        self.comboBox_width_a.setItemText(2, _translate("aquisition_setup", "ms"))
        self.comboBox_width_a.setItemText(3, _translate("aquisition_setup", "s"))
        self.label_23.setText(_translate("aquisition_setup", "延时"))
        self.label_24.setText(_translate("aquisition_setup", "极性"))
        self.comboBox_polarity_a.setItemText(0, _translate("aquisition_setup", "正"))
        self.comboBox_polarity_a.setItemText(1, _translate("aquisition_setup", "反"))
        self.checkBox_same_to_gate_a.setText(_translate("aquisition_setup", "与门控一致"))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.tab_6), _translate("aquisition_setup", "输出A"))
        self.checkBox_channel_enable_b.setText(_translate("aquisition_setup", "开启"))
        self.label_25.setText(_translate("aquisition_setup", "脉宽"))
        self.comboBox_delay_b.setItemText(0, _translate("aquisition_setup", "ps"))
        self.comboBox_delay_b.setItemText(1, _translate("aquisition_setup", "ns"))
        self.comboBox_delay_b.setItemText(2, _translate("aquisition_setup", "us"))
        self.comboBox_delay_b.setItemText(3, _translate("aquisition_setup", "ms"))
        self.comboBox_delay_b.setItemText(4, _translate("aquisition_setup", "s"))
        self.comboBox_width_b.setItemText(0, _translate("aquisition_setup", "ns"))
        self.comboBox_width_b.setItemText(1, _translate("aquisition_setup", "us"))
        self.comboBox_width_b.setItemText(2, _translate("aquisition_setup", "ms"))
        self.comboBox_width_b.setItemText(3, _translate("aquisition_setup", "s"))
        self.label_26.setText(_translate("aquisition_setup", "延时"))
        self.label_27.setText(_translate("aquisition_setup", "极性"))
        self.comboBox_polarity_b.setItemText(0, _translate("aquisition_setup", "正"))
        self.comboBox_polarity_b.setItemText(1, _translate("aquisition_setup", "反"))
        self.checkBox_same_to_gate_b.setText(_translate("aquisition_setup", "与门控一致"))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.tab_7), _translate("aquisition_setup", "输出B"))
        self.checkBox_channel_enable_c.setText(_translate("aquisition_setup", "开启"))
        self.label_28.setText(_translate("aquisition_setup", "脉宽"))
        self.comboBox_delay_c.setItemText(0, _translate("aquisition_setup", "ps"))
        self.comboBox_delay_c.setItemText(1, _translate("aquisition_setup", "ns"))
        self.comboBox_delay_c.setItemText(2, _translate("aquisition_setup", "us"))
        self.comboBox_delay_c.setItemText(3, _translate("aquisition_setup", "ms"))
        self.comboBox_delay_c.setItemText(4, _translate("aquisition_setup", "s"))
        self.comboBox_width_c.setItemText(0, _translate("aquisition_setup", "ns"))
        self.comboBox_width_c.setItemText(1, _translate("aquisition_setup", "us"))
        self.comboBox_width_c.setItemText(2, _translate("aquisition_setup", "ms"))
        self.comboBox_width_c.setItemText(3, _translate("aquisition_setup", "s"))
        self.label_29.setText(_translate("aquisition_setup", "延时"))
        self.label_30.setText(_translate("aquisition_setup", "极性"))
        self.comboBox_polarity_c.setItemText(0, _translate("aquisition_setup", "正"))
        self.comboBox_polarity_c.setItemText(1, _translate("aquisition_setup", "反"))
        self.checkBox_same_to_gate_c.setText(_translate("aquisition_setup", "与门控一致"))
        self.tabWidget_output.setTabText(self.tabWidget_output.indexOf(self.tab_8), _translate("aquisition_setup", "输出C"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("aquisition_setup", "门控设置"))
        self.groupBox_4.setTitle(_translate("aquisition_setup", "局部区域"))
        self.label_11.setText(_translate("aquisition_setup", "右"))
        self.label_12.setText(_translate("aquisition_setup", "顶部"))
        self.label_9.setText(_translate("aquisition_setup", " 左"))
        self.label_10.setText(_translate("aquisition_setup", "底部"))
        self.label_16.setText(_translate("aquisition_setup", "宽"))
        self.label_17.setText(_translate("aquisition_setup", "高"))
        self.pushButton_roi_sure.setText(_translate("aquisition_setup", "确认"))
        self.pushButton_revoke.setText(_translate("aquisition_setup", "撤销"))
        self.pushButton_roi_resume.setText(_translate("aquisition_setup", "恢复初始尺寸"))
        self.groupBox_5.setTitle(_translate("aquisition_setup", "Binning"))
        self.radioButton_binning1.setText(_translate("aquisition_setup", "禁用"))
        self.radioButton_binning2.setText(_translate("aquisition_setup", "2X2"))
        self.radioButton_binning3.setText(_translate("aquisition_setup", "1X2"))
        self.radioButton_binning4.setText(_translate("aquisition_setup", "2X1"))
        self.label_32.setText(_translate("aquisition_setup", "*2X1横向合并纵向不变"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("aquisition_setup", "Binning/ROI"))
        self.checkBox_enable_autosave.setText(_translate("aquisition_setup", "启用"))
        self.label_13.setText(_translate("aquisition_setup", "文件格式"))
        self.label_14.setText(_translate("aquisition_setup", "文件名"))
        self.lineEdit_file_name.setText(_translate("aquisition_setup", "Image"))
        self.checkBox_date.setText(_translate("aquisition_setup", "日期"))
        self.lineEdit_file_path.setText(_translate("aquisition_setup", "C:\\"))
        self.pushButton_choose_filepath.setText(_translate("aquisition_setup", "文件夹"))
        self.comboBox_file_format.setItemText(0, _translate("aquisition_setup", ".tiff"))
        self.comboBox_file_format.setItemText(1, _translate("aquisition_setup", ".jpg"))
        self.comboBox_file_format.setItemText(2, _translate("aquisition_setup", ".png"))
        self.comboBox_file_format.setItemText(3, _translate("aquisition_setup", ".csv"))
        self.checkBox_operator.setText(_translate("aquisition_setup", "操作者"))
        self.lineEdit_operator.setText(_translate("aquisition_setup", "admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("aquisition_setup", "自动保存"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aquisition_setup = QtWidgets.QWidget()
    ui = Ui_aquisition_setup()
    ui.setupUi(aquisition_setup)
    aquisition_setup.show()
    sys.exit(app.exec_())

