# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ProgramProjects\graph_widget\graph_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico/sc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget_3D = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3D.setBaseSize(QtCore.QSize(0, 300))
        self.dockWidget_3D.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_3D.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_3D.setObjectName("dockWidget_3D")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3D = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D.setObjectName("verticalLayout_3D")
        self.label_3D = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3D.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3D.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3D.setObjectName("label_3D")
        self.verticalLayout_3D.addWidget(self.label_3D)
        self.horizontalLayout_slider = QtWidgets.QHBoxLayout()
        self.horizontalLayout_slider.setObjectName("horizontalLayout_slider")
        self.toolButton_advance = QtWidgets.QToolButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/ico/1225467.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_advance.setIcon(icon1)
        self.toolButton_advance.setObjectName("toolButton_advance")
        self.horizontalLayout_slider.addWidget(self.toolButton_advance)
        self.horizontalSlider_3d = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSlider_3d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3d.setObjectName("horizontalSlider_3d")
        self.horizontalLayout_slider.addWidget(self.horizontalSlider_3d)
        self.toolButton_next = QtWidgets.QToolButton(self.dockWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/ico/1209014.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_next.setIcon(icon2)
        self.toolButton_next.setObjectName("toolButton_next")
        self.horizontalLayout_slider.addWidget(self.toolButton_next)
        self.verticalLayout_3D.addLayout(self.horizontalLayout_slider)
        self.verticalLayout_3.addLayout(self.verticalLayout_3D)
        self.dockWidget_3D.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_3D)
        self.dockWidget_image = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_image.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget_image.setObjectName("dockWidget_image")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_image = QtWidgets.QVBoxLayout()
        self.verticalLayout_image.setObjectName("verticalLayout_image")
        self.label_image = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_image.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_image.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_image.setObjectName("label_image")
        self.verticalLayout_image.addWidget(self.label_image)
        self.verticalLayout_8.addLayout(self.verticalLayout_image)
        self.dockWidget_image.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_image)
        self.dockWidget_binning_vertical = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_binning_vertical.setBaseSize(QtCore.QSize(0, 200))
        self.dockWidget_binning_vertical.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_binning_vertical.setObjectName("dockWidget_binning_vertical")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_binning_vertical = QtWidgets.QVBoxLayout()
        self.verticalLayout_binning_vertical.setObjectName("verticalLayout_binning_vertical")
        self.label_vertical = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_vertical.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_vertical.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_vertical.setObjectName("label_vertical")
        self.verticalLayout_binning_vertical.addWidget(self.label_vertical)
        self.verticalLayout_9.addLayout(self.verticalLayout_binning_vertical)
        self.dockWidget_binning_vertical.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_binning_vertical)
        self.dockWidget_message = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_message.setEnabled(True)
        self.dockWidget_message.setMaximumSize(QtCore.QSize(200, 524287))
        self.dockWidget_message.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_message.setObjectName("dockWidget_message")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_hist = QtWidgets.QVBoxLayout()
        self.verticalLayout_hist.setObjectName("verticalLayout_hist")
        self.label_hist = QtWidgets.QLabel(self.dockWidgetContents_4)
        self.label_hist.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_hist.setObjectName("label_hist")
        self.verticalLayout_hist.addWidget(self.label_hist)
        self.verticalLayout.addLayout(self.verticalLayout_hist)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.dockWidget_message.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_message)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_binning_horizontal = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_binning_horizontal.setMaximumSize(QtCore.QSize(300, 524287))
        self.dockWidget_binning_horizontal.setBaseSize(QtCore.QSize(200, 0))
        self.dockWidget_binning_horizontal.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_binning_horizontal.setObjectName("dockWidget_binning_horizontal")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.dockWidgetContents_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_binning_horizontal = QtWidgets.QVBoxLayout()
        self.verticalLayout_binning_horizontal.setObjectName("verticalLayout_binning_horizontal")
        self.label_horizontal = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_horizontal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_horizontal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_horizontal.setObjectName("label_horizontal")
        self.verticalLayout_binning_horizontal.addWidget(self.label_horizontal)
        self.verticalLayout_10.addLayout(self.verticalLayout_binning_horizontal)
        self.dockWidget_binning_horizontal.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_binning_horizontal)
        self.dockWidget_roi_line = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_roi_line.setBaseSize(QtCore.QSize(0, 200))
        self.dockWidget_roi_line.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_roi_line.setObjectName("dockWidget_roi_line")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_roi_line = QtWidgets.QVBoxLayout()
        self.verticalLayout_roi_line.setObjectName("verticalLayout_roi_line")
        self.label_roiline = QtWidgets.QLabel(self.dockWidgetContents_5)
        self.label_roiline.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_roiline.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_roiline.setObjectName("label_roiline")
        self.verticalLayout_roi_line.addWidget(self.label_roiline)
        self.verticalLayout_4.addLayout(self.verticalLayout_roi_line)
        self.dockWidget_roi_line.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_roi_line)
        self.action_display_message = QtWidgets.QAction(MainWindow)
        self.action_display_message.setCheckable(True)
        self.action_display_message.setObjectName("action_display_message")
        self.action_vertical_binning = QtWidgets.QAction(MainWindow)
        self.action_vertical_binning.setCheckable(True)
        self.action_vertical_binning.setObjectName("action_vertical_binning")
        self.action_binning2x2 = QtWidgets.QAction(MainWindow)
        self.action_binning2x2.setCheckable(True)
        self.action_binning2x2.setObjectName("action_binning2x2")
        self.action_roi_rectangle = QtWidgets.QAction(MainWindow)
        self.action_roi_rectangle.setCheckable(True)
        self.action_roi_rectangle.setObjectName("action_roi_rectangle")
        self.action_roi_line = QtWidgets.QAction(MainWindow)
        self.action_roi_line.setCheckable(True)
        self.action_roi_line.setObjectName("action_roi_line")
        self.action_3D = QtWidgets.QAction(MainWindow)
        self.action_3D.setCheckable(True)
        self.action_3D.setObjectName("action_3D")
        self.action_horizontal_binning = QtWidgets.QAction(MainWindow)
        self.action_horizontal_binning.setCheckable(True)
        self.action_horizontal_binning.setObjectName("action_horizontal_binning")
        self.toolBar.addAction(self.action_3D)
        self.toolBar.addAction(self.action_roi_line)
        self.toolBar.addAction(self.action_vertical_binning)
        self.toolBar.addAction(self.action_horizontal_binning)
        self.toolBar.addAction(self.action_roi_rectangle)
        self.toolBar.addAction(self.action_binning2x2)
        self.toolBar.addAction(self.action_display_message)

        self.retranslateUi(MainWindow)
        self.dockWidget_3D.visibilityChanged['bool'].connect(self.action_3D.setChecked)
        self.action_3D.triggered['bool'].connect(self.dockWidget_3D.setVisible)
        self.dockWidget_binning_vertical.visibilityChanged['bool'].connect(self.action_vertical_binning.setChecked)
        self.dockWidget_binning_horizontal.visibilityChanged['bool'].connect(self.action_horizontal_binning.setChecked)
        self.dockWidget_message.visibilityChanged['bool'].connect(self.action_display_message.setChecked)
        self.action_vertical_binning.triggered['bool'].connect(self.dockWidget_binning_vertical.setVisible)
        self.action_horizontal_binning.triggered['bool'].connect(self.dockWidget_binning_horizontal.setVisible)
        self.action_display_message.triggered['bool'].connect(self.dockWidget_message.setVisible)
        self.dockWidget_roi_line.visibilityChanged['bool'].connect(self.action_roi_line.setChecked)
        self.action_roi_line.triggered['bool'].connect(self.dockWidget_roi_line.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "graph_widget"))
        self.dockWidget_3D.setWindowTitle(_translate("MainWindow", "图像阵列"))
        self.label_3D.setText(_translate("MainWindow", "图像：0"))
        self.toolButton_advance.setText(_translate("MainWindow", "..."))
        self.toolButton_next.setText(_translate("MainWindow", "..."))
        self.dockWidget_image.setWindowTitle(_translate("MainWindow", "图像显示"))
        self.label_image.setText(_translate("MainWindow", "X,Y=0.00,0.00  Value=0.00"))
        self.dockWidget_binning_vertical.setWindowTitle(_translate("MainWindow", "纵向合并"))
        self.label_vertical.setText(_translate("MainWindow", "X=0.00,Y=0.00"))
        self.dockWidget_message.setWindowTitle(_translate("MainWindow", "信息展示"))
        self.label_hist.setText(_translate("MainWindow", "色阶"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_binning_horizontal.setWindowTitle(_translate("MainWindow", "横向合并"))
        self.label_horizontal.setText(_translate("MainWindow", "X=0.00,Y=0.00"))
        self.dockWidget_roi_line.setWindowTitle(_translate("MainWindow", "局部线"))
        self.label_roiline.setText(_translate("MainWindow", "X=0.00,Y=0.00"))
        self.action_display_message.setText(_translate("MainWindow", "显示信息"))
        self.action_vertical_binning.setText(_translate("MainWindow", "纵向合并"))
        self.action_binning2x2.setText(_translate("MainWindow", "像素合并2x2"))
        self.action_roi_rectangle.setText(_translate("MainWindow", "局部矩形框"))
        self.action_roi_line.setText(_translate("MainWindow", "局部线"))
        self.action_3D.setText(_translate("MainWindow", "3D展示"))
        self.action_horizontal_binning.setText(_translate("MainWindow", "横向合并"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

