# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ProgramProjects\ICCD1.0\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(942, 570)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico_file/ICCD图标zip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_status = QtWidgets.QWidget(self.centralWidget)
        self.widget_status.setObjectName("widget_status")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_status)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_resolution_title = QtWidgets.QLabel(self.widget_status)
        self.label_resolution_title.setObjectName("label_resolution_title")
        self.horizontalLayout_2.addWidget(self.label_resolution_title)
        self.label_resolution_value = QtWidgets.QLabel(self.widget_status)
        self.label_resolution_value.setObjectName("label_resolution_value")
        self.horizontalLayout_2.addWidget(self.label_resolution_value)
        self.label_frame_title = QtWidgets.QLabel(self.widget_status)
        self.label_frame_title.setObjectName("label_frame_title")
        self.horizontalLayout_2.addWidget(self.label_frame_title)
        self.doubleSpinBox_frame_value = QtWidgets.QDoubleSpinBox(self.widget_status)
        self.doubleSpinBox_frame_value.setEnabled(False)
        self.doubleSpinBox_frame_value.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_frame_value.setMaximum(10000.0)
        self.doubleSpinBox_frame_value.setObjectName("doubleSpinBox_frame_value")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_frame_value)
        self.horizontalLayout.addWidget(self.widget_status)
        self.label_connect_title = QtWidgets.QLabel(self.centralWidget)
        self.label_connect_title.setObjectName("label_connect_title")
        self.horizontalLayout.addWidget(self.label_connect_title)
        self.label_connect_value = QtWidgets.QLabel(self.centralWidget)
        self.label_connect_value.setMinimumSize(QtCore.QSize(20, 20))
        self.label_connect_value.setMaximumSize(QtCore.QSize(20, 20))
        self.label_connect_value.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.label_connect_value.setText("")
        self.label_connect_value.setObjectName("label_connect_value")
        self.horizontalLayout.addWidget(self.label_connect_value)
        self.toolButton_realtime = QtWidgets.QToolButton(self.centralWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/ico_file/1163683.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_realtime.setIcon(icon1)
        self.toolButton_realtime.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_realtime.setCheckable(True)
        self.toolButton_realtime.setAutoExclusive(True)
        self.toolButton_realtime.setObjectName("toolButton_realtime")
        self.horizontalLayout.addWidget(self.toolButton_realtime)
        self.toolButton_take_signal = QtWidgets.QToolButton(self.centralWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/ico_file/1157134.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_take_signal.setIcon(icon2)
        self.toolButton_take_signal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_take_signal.setCheckable(True)
        self.toolButton_take_signal.setAutoExclusive(True)
        self.toolButton_take_signal.setObjectName("toolButton_take_signal")
        self.horizontalLayout.addWidget(self.toolButton_take_signal)
        self.toolButton_stop = QtWidgets.QToolButton(self.centralWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/ico_file/1186323.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_stop.setIcon(icon3)
        self.toolButton_stop.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_stop.setCheckable(True)
        self.toolButton_stop.setAutoExclusive(True)
        self.toolButton_stop.setObjectName("toolButton_stop")
        self.horizontalLayout.addWidget(self.toolButton_stop)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mdiArea.setActivationOrder(QtWidgets.QMdiArea.StackingOrder)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.TabbedView)
        self.mdiArea.setDocumentMode(True)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabPosition(QtWidgets.QTabWidget.South)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 942, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menu.setTearOffEnabled(False)
        self.menu.setSeparatorsCollapsible(False)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setTearOffEnabled(False)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_aquisition_setup = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/ico_file/1117367.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/ico/C:/Users/30294/Desktop/ico/ico_file/1117367.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_aquisition_setup.setIcon(icon4)
        self.action_aquisition_setup.setAutoRepeat(False)
        self.action_aquisition_setup.setObjectName("action_aquisition_setup")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setCheckable(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/ico_file/1187725.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon5)
        self.action_save.setAutoRepeat(False)
        self.action_save.setObjectName("action_save")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setCheckable(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/ico_file/1148238.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon6)
        self.action_open.setAutoRepeat(False)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ico/ico_file/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon7)
        self.action_exit.setAutoRepeat(False)
        self.action_exit.setObjectName("action_exit")
        self.action_synch = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ico/ico_file/yunxingshi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_synch.setIcon(icon8)
        self.action_synch.setAutoRepeat(False)
        self.action_synch.setObjectName("action_synch")
        self.action_tiling = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ico/ico_file/1075159.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_tiling.setIcon(icon9)
        self.action_tiling.setObjectName("action_tiling")
        self.action_cascade = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/ico/ico_file/526693.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cascade.setIcon(icon10)
        self.action_cascade.setObjectName("action_cascade")
        self.action_clear = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/ico/ico_file/1201008.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clear.setIcon(icon11)
        self.action_clear.setObjectName("action_clear")
        self.action_subwindow = QtWidgets.QAction(MainWindow)
        self.action_subwindow.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/ico/ico_file/1131551.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_subwindow.setIcon(icon12)
        self.action_subwindow.setObjectName("action_subwindow")
        self.action_open_sequence_file = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/ico/ico_file/1072492.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_sequence_file.setIcon(icon13)
        self.action_open_sequence_file.setObjectName("action_open_sequence_file")
        self.action_save_sequence_file = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/ico/ico_file/1072697.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_sequence_file.setIcon(icon14)
        self.action_save_sequence_file.setObjectName("action_save_sequence_file")
        self.action_save_config = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/ico/ico_file/1143888.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_config.setIcon(icon15)
        self.action_save_config.setObjectName("action_save_config")
        self.action_open_config = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/ico/ico_file/1140575.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_config.setIcon(icon16)
        self.action_open_config.setObjectName("action_open_config")
        self.action_save_config_todevice = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/ico/ico_file/1187937.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_config_todevice.setIcon(icon17)
        self.action_save_config_todevice.setObjectName("action_save_config_todevice")
        self.action_load_deviece_config = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/ico/ico_file/1189501.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_load_deviece_config.setIcon(icon18)
        self.action_load_deviece_config.setObjectName("action_load_deviece_config")
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_open_sequence_file)
        self.menu.addAction(self.action_save_sequence_file)
        self.menu.addAction(self.action_save_config_todevice)
        self.menu.addAction(self.action_load_deviece_config)
        self.menu.addAction(self.action_open_config)
        self.menu.addAction(self.action_save_config)
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.action_aquisition_setup)
        self.menu_2.addAction(self.action_synch)
        self.menu_2.addSeparator()
        self.menu_3.addAction(self.action_tiling)
        self.menu_3.addAction(self.action_cascade)
        self.menu_3.addAction(self.action_clear)
        self.menu_3.addAction(self.action_subwindow)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.action_save)
        self.toolBar.addAction(self.action_open)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(self.toolButton_realtime)
        self.toolBar.addWidget(self.toolButton_take_signal)
        self.toolBar.addWidget(self.toolButton_stop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_aquisition_setup)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_synch)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_tiling)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_cascade)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_clear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_subwindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.toolButton_realtime, self.toolButton_take_signal)
        MainWindow.setTabOrder(self.toolButton_take_signal, self.toolButton_stop)
        MainWindow.setTabOrder(self.toolButton_stop, self.doubleSpinBox_frame_value)
        self.statusBar.addWidget(self.widget_status)
        self.statusBar.addWidget(self.progressBar)
        self.statusBar.addPermanentWidget(self.label_connect_title)
        self.statusBar.addPermanentWidget(self.label_connect_value)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Capture"))
        self.label_resolution_title.setText(_translate("MainWindow", "分辨率"))
        self.label_resolution_value.setText(_translate("MainWindow", "0x0"))
        self.label_frame_title.setText(_translate("MainWindow", "帧速"))
        self.label_connect_title.setText(_translate("MainWindow", "连接状态"))
        self.toolButton_realtime.setText(_translate("MainWindow", "..."))
        self.toolButton_take_signal.setText(_translate("MainWindow", "..."))
        self.toolButton_stop.setText(_translate("MainWindow", "..."))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "采集"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_aquisition_setup.setText(_translate("MainWindow", "采集设置"))
        self.action_aquisition_setup.setShortcut(_translate("MainWindow", "F1"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.action_synch.setText(_translate("MainWindow", "同步设置"))
        self.action_tiling.setText(_translate("MainWindow", "平铺"))
        self.action_cascade.setText(_translate("MainWindow", "级联"))
        self.action_clear.setText(_translate("MainWindow", "清除"))
        self.action_subwindow.setText(_translate("MainWindow", "子窗口模式"))
        self.action_open_sequence_file.setText(_translate("MainWindow", "打开序列"))
        self.action_save_sequence_file.setText(_translate("MainWindow", "保存序列"))
        self.action_save_config.setText(_translate("MainWindow", "保存配置文件"))
        self.action_save_config.setToolTip(_translate("MainWindow", "保存配置文件"))
        self.action_open_config.setText(_translate("MainWindow", "加载配置文件"))
        self.action_open_config.setToolTip(_translate("MainWindow", "打开配置"))
        self.action_save_config_todevice.setText(_translate("MainWindow", "保存配置"))
        self.action_load_deviece_config.setText(_translate("MainWindow", "加载配置"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

