# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ProgramProjects\ICCD1.0\runtime_control.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_runtime_control(object):
    def setupUi(self, runtime_control):
        runtime_control.setObjectName("runtime_control")
        runtime_control.resize(250, 186)
        runtime_control.setMinimumSize(QtCore.QSize(0, 0))
        runtime_control.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico_file/yunxingshi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        runtime_control.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(runtime_control)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_output_setup = QtWidgets.QTabWidget(runtime_control)
        self.tabWidget_output_setup.setMaximumSize(QtCore.QSize(16777215, 5000))
        self.tabWidget_output_setup.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_output_setup.setObjectName("tabWidget_output_setup")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_delay_d = QtWidgets.QComboBox(self.tab)
        self.comboBox_delay_d.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_delay_d.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_delay_d.setObjectName("comboBox_delay_d")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.comboBox_delay_d.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_delay_d, 0, 2, 1, 1)
        self.doubleSpinBox_delay_d = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_delay_d.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_delay_d.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_delay_d.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_d.setObjectName("doubleSpinBox_delay_d")
        self.gridLayout_4.addWidget(self.doubleSpinBox_delay_d, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_width_d = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_width_d.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_width_d.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_width_d.setMaximum(1000000000.0)
        self.doubleSpinBox_width_d.setObjectName("doubleSpinBox_width_d")
        self.gridLayout_4.addWidget(self.doubleSpinBox_width_d, 1, 1, 1, 1)
        self.comboBox_width_d = QtWidgets.QComboBox(self.tab)
        self.comboBox_width_d.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_width_d.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_width_d.setObjectName("comboBox_width_d")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.comboBox_width_d.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_width_d, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.tabWidget_output_setup.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_channel_enable_a = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_channel_enable_a.setObjectName("checkBox_channel_enable_a")
        self.verticalLayout_2.addWidget(self.checkBox_channel_enable_a)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.doubleSpinBox_delay_a = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_delay_a.setEnabled(False)
        self.doubleSpinBox_delay_a.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_delay_a.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_delay_a.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_a.setObjectName("doubleSpinBox_delay_a")
        self.gridLayout_8.addWidget(self.doubleSpinBox_delay_a, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 1, 0, 1, 1)
        self.doubleSpinBox_width_a = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_width_a.setEnabled(False)
        self.doubleSpinBox_width_a.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_width_a.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_width_a.setMaximum(1000000000.0)
        self.doubleSpinBox_width_a.setObjectName("doubleSpinBox_width_a")
        self.gridLayout_8.addWidget(self.doubleSpinBox_width_a, 1, 1, 1, 1)
        self.comboBox_delay_a = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_delay_a.setEnabled(False)
        self.comboBox_delay_a.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_delay_a.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_delay_a.setObjectName("comboBox_delay_a")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.comboBox_delay_a.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_delay_a, 0, 2, 1, 1)
        self.comboBox_width_a = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_width_a.setEnabled(False)
        self.comboBox_width_a.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_width_a.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_width_a.setObjectName("comboBox_width_a")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.comboBox_width_a.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_width_a, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.tabWidget_output_setup.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_channel_enable_b = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_channel_enable_b.setObjectName("checkBox_channel_enable_b")
        self.verticalLayout_3.addWidget(self.checkBox_channel_enable_b)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.doubleSpinBox_delay_b = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_delay_b.setEnabled(False)
        self.doubleSpinBox_delay_b.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_delay_b.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_delay_b.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_b.setObjectName("doubleSpinBox_delay_b")
        self.gridLayout_9.addWidget(self.doubleSpinBox_delay_b, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.doubleSpinBox_width_b = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_width_b.setEnabled(False)
        self.doubleSpinBox_width_b.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_width_b.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_width_b.setMaximum(1000000000.0)
        self.doubleSpinBox_width_b.setObjectName("doubleSpinBox_width_b")
        self.gridLayout_9.addWidget(self.doubleSpinBox_width_b, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_delay_b = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_delay_b.setEnabled(False)
        self.comboBox_delay_b.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_delay_b.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_delay_b.setObjectName("comboBox_delay_b")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.comboBox_delay_b.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_delay_b, 1, 2, 1, 1)
        self.comboBox_width_b = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_width_b.setEnabled(False)
        self.comboBox_width_b.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_width_b.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_width_b.setObjectName("comboBox_width_b")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.comboBox_width_b.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_width_b, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_9)
        self.tabWidget_output_setup.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_channel_enable_c = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_channel_enable_c.setObjectName("checkBox_channel_enable_c")
        self.verticalLayout_4.addWidget(self.checkBox_channel_enable_c)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.doubleSpinBox_delay_c = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_delay_c.setEnabled(False)
        self.doubleSpinBox_delay_c.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_delay_c.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_delay_c.setMaximum(1000000000.0)
        self.doubleSpinBox_delay_c.setObjectName("doubleSpinBox_delay_c")
        self.gridLayout_10.addWidget(self.doubleSpinBox_delay_c, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 1, 0, 1, 1)
        self.doubleSpinBox_width_c = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_width_c.setEnabled(False)
        self.doubleSpinBox_width_c.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_width_c.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_width_c.setMaximum(1000000000.0)
        self.doubleSpinBox_width_c.setObjectName("doubleSpinBox_width_c")
        self.gridLayout_10.addWidget(self.doubleSpinBox_width_c, 1, 1, 1, 1)
        self.comboBox_delay_c = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_delay_c.setEnabled(False)
        self.comboBox_delay_c.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_delay_c.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_delay_c.setObjectName("comboBox_delay_c")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.comboBox_delay_c.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_delay_c, 0, 2, 1, 1)
        self.comboBox_width_c = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_width_c.setEnabled(False)
        self.comboBox_width_c.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBox_width_c.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.comboBox_width_c.setObjectName("comboBox_width_c")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.comboBox_width_c.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_width_c, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_10)
        self.tabWidget_output_setup.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget_output_setup)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_exposure = QtWidgets.QDoubleSpinBox(runtime_control)
        self.doubleSpinBox_exposure.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_exposure.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.doubleSpinBox_exposure.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_exposure.setDecimals(5)
        self.doubleSpinBox_exposure.setMinimum(0.00025)
        self.doubleSpinBox_exposure.setMaximum(30.0)
        self.doubleSpinBox_exposure.setSingleStep(0.001)
        self.doubleSpinBox_exposure.setObjectName("doubleSpinBox_exposure")
        self.gridLayout_3.addWidget(self.doubleSpinBox_exposure, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(runtime_control)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(runtime_control)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_mcp_gain = QtWidgets.QSpinBox(runtime_control)
        self.spinBox_mcp_gain.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_mcp_gain.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.spinBox_mcp_gain.setMaximum(4095)
        self.spinBox_mcp_gain.setSingleStep(100)
        self.spinBox_mcp_gain.setObjectName("spinBox_mcp_gain")
        self.gridLayout_3.addWidget(self.spinBox_mcp_gain, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(runtime_control)
        self.tabWidget_output_setup.setCurrentIndex(0)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.doubleSpinBox_delay_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.doubleSpinBox_width_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.comboBox_delay_a.setEnabled)
        self.checkBox_channel_enable_a.toggled['bool'].connect(self.comboBox_width_a.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.doubleSpinBox_delay_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.doubleSpinBox_width_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.comboBox_delay_b.setEnabled)
        self.checkBox_channel_enable_b.toggled['bool'].connect(self.comboBox_width_b.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.doubleSpinBox_delay_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.doubleSpinBox_width_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.comboBox_delay_c.setEnabled)
        self.checkBox_channel_enable_c.toggled['bool'].connect(self.comboBox_width_c.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(runtime_control)
        runtime_control.setTabOrder(self.tabWidget_output_setup, self.doubleSpinBox_delay_d)
        runtime_control.setTabOrder(self.doubleSpinBox_delay_d, self.comboBox_delay_d)
        runtime_control.setTabOrder(self.comboBox_delay_d, self.doubleSpinBox_width_d)
        runtime_control.setTabOrder(self.doubleSpinBox_width_d, self.comboBox_width_d)
        runtime_control.setTabOrder(self.comboBox_width_d, self.doubleSpinBox_exposure)
        runtime_control.setTabOrder(self.doubleSpinBox_exposure, self.spinBox_mcp_gain)
        runtime_control.setTabOrder(self.spinBox_mcp_gain, self.checkBox_channel_enable_a)
        runtime_control.setTabOrder(self.checkBox_channel_enable_a, self.doubleSpinBox_delay_a)
        runtime_control.setTabOrder(self.doubleSpinBox_delay_a, self.comboBox_delay_a)
        runtime_control.setTabOrder(self.comboBox_delay_a, self.doubleSpinBox_width_a)
        runtime_control.setTabOrder(self.doubleSpinBox_width_a, self.comboBox_width_a)
        runtime_control.setTabOrder(self.comboBox_width_a, self.checkBox_channel_enable_b)
        runtime_control.setTabOrder(self.checkBox_channel_enable_b, self.doubleSpinBox_delay_b)
        runtime_control.setTabOrder(self.doubleSpinBox_delay_b, self.comboBox_delay_b)
        runtime_control.setTabOrder(self.comboBox_delay_b, self.doubleSpinBox_width_b)
        runtime_control.setTabOrder(self.doubleSpinBox_width_b, self.comboBox_width_b)
        runtime_control.setTabOrder(self.comboBox_width_b, self.checkBox_channel_enable_c)
        runtime_control.setTabOrder(self.checkBox_channel_enable_c, self.doubleSpinBox_delay_c)
        runtime_control.setTabOrder(self.doubleSpinBox_delay_c, self.comboBox_delay_c)
        runtime_control.setTabOrder(self.comboBox_delay_c, self.doubleSpinBox_width_c)
        runtime_control.setTabOrder(self.doubleSpinBox_width_c, self.comboBox_width_c)

    def retranslateUi(self, runtime_control):
        _translate = QtCore.QCoreApplication.translate
        runtime_control.setWindowTitle(_translate("runtime_control", "基础设置"))
        self.label.setText(_translate("runtime_control", "延时"))
        self.comboBox_delay_d.setItemText(0, _translate("runtime_control", "ps"))
        self.comboBox_delay_d.setItemText(1, _translate("runtime_control", "ns"))
        self.comboBox_delay_d.setItemText(2, _translate("runtime_control", "us"))
        self.comboBox_delay_d.setItemText(3, _translate("runtime_control", "ms"))
        self.comboBox_delay_d.setItemText(4, _translate("runtime_control", "s"))
        self.label_2.setText(_translate("runtime_control", "脉宽"))
        self.comboBox_width_d.setItemText(0, _translate("runtime_control", "ns"))
        self.comboBox_width_d.setItemText(1, _translate("runtime_control", "us"))
        self.comboBox_width_d.setItemText(2, _translate("runtime_control", "ms"))
        self.comboBox_width_d.setItemText(3, _translate("runtime_control", "s"))
        self.tabWidget_output_setup.setTabText(self.tabWidget_output_setup.indexOf(self.tab), _translate("runtime_control", "门控"))
        self.checkBox_channel_enable_a.setText(_translate("runtime_control", "开启"))
        self.label_7.setText(_translate("runtime_control", "延时"))
        self.label_8.setText(_translate("runtime_control", "脉宽"))
        self.comboBox_delay_a.setItemText(0, _translate("runtime_control", "ps"))
        self.comboBox_delay_a.setItemText(1, _translate("runtime_control", "ns"))
        self.comboBox_delay_a.setItemText(2, _translate("runtime_control", "us"))
        self.comboBox_delay_a.setItemText(3, _translate("runtime_control", "ms"))
        self.comboBox_delay_a.setItemText(4, _translate("runtime_control", "s"))
        self.comboBox_width_a.setItemText(0, _translate("runtime_control", "ns"))
        self.comboBox_width_a.setItemText(1, _translate("runtime_control", "us"))
        self.comboBox_width_a.setItemText(2, _translate("runtime_control", "ms"))
        self.comboBox_width_a.setItemText(3, _translate("runtime_control", "s"))
        self.tabWidget_output_setup.setTabText(self.tabWidget_output_setup.indexOf(self.tab_2), _translate("runtime_control", "输出A"))
        self.checkBox_channel_enable_b.setText(_translate("runtime_control", "开启"))
        self.label_10.setText(_translate("runtime_control", "脉宽"))
        self.label_9.setText(_translate("runtime_control", "延时"))
        self.comboBox_delay_b.setItemText(0, _translate("runtime_control", "ps"))
        self.comboBox_delay_b.setItemText(1, _translate("runtime_control", "ns"))
        self.comboBox_delay_b.setItemText(2, _translate("runtime_control", "us"))
        self.comboBox_delay_b.setItemText(3, _translate("runtime_control", "ms"))
        self.comboBox_delay_b.setItemText(4, _translate("runtime_control", "s"))
        self.comboBox_width_b.setItemText(0, _translate("runtime_control", "ns"))
        self.comboBox_width_b.setItemText(1, _translate("runtime_control", "us"))
        self.comboBox_width_b.setItemText(2, _translate("runtime_control", "ms"))
        self.comboBox_width_b.setItemText(3, _translate("runtime_control", "s"))
        self.tabWidget_output_setup.setTabText(self.tabWidget_output_setup.indexOf(self.tab_3), _translate("runtime_control", "输出B"))
        self.checkBox_channel_enable_c.setText(_translate("runtime_control", "开启"))
        self.label_11.setText(_translate("runtime_control", "延时"))
        self.label_12.setText(_translate("runtime_control", "脉宽"))
        self.comboBox_delay_c.setItemText(0, _translate("runtime_control", "ps"))
        self.comboBox_delay_c.setItemText(1, _translate("runtime_control", "ns"))
        self.comboBox_delay_c.setItemText(2, _translate("runtime_control", "us"))
        self.comboBox_delay_c.setItemText(3, _translate("runtime_control", "ms"))
        self.comboBox_delay_c.setItemText(4, _translate("runtime_control", "s"))
        self.comboBox_width_c.setItemText(0, _translate("runtime_control", "ns"))
        self.comboBox_width_c.setItemText(1, _translate("runtime_control", "us"))
        self.comboBox_width_c.setItemText(2, _translate("runtime_control", "ms"))
        self.comboBox_width_c.setItemText(3, _translate("runtime_control", "s"))
        self.tabWidget_output_setup.setTabText(self.tabWidget_output_setup.indexOf(self.tab_4), _translate("runtime_control", "输出C"))
        self.label_3.setText(_translate("runtime_control", "曝光时间(S)"))
        self.label_4.setText(_translate("runtime_control", "MCP增益(0-4095)"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    runtime_control = QtWidgets.QWidget()
    ui = Ui_runtime_control()
    ui.setupUi(runtime_control)
    runtime_control.show()
    sys.exit(app.exec_())

